export const ACCOUNT_HASH_RECEIVED = 'ACCOUNT_HASH_RECEIVED';

export const REQUEST_PROFILE = 'REQUEST_PROFILE';
export const PROFILE_RECEIVED = 'PROFILE_RECEIVED';
export const PROFILE_REMOVED = 'PROFILE_REMOVED';

export const REQUEST_USER_PERMISSION = 'REQUEST_USER_PERMISSION';
export const USER_PERMISSION_RECEIVED = 'USER_PERMISSION_RECEIVED';

export const REQUEST_PROFILES = 'REQUEST_PROFILES';

export const REQUEST_REFILL = 'REQUEST_REFILL';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const REMOVE_PROFILE = 'REMOVE_PROFILE';
export const ADD_PROFILE = 'ADD_PROFILE';
export const ADD_USER_PERMISSION = 'ADD_USER_PERMISSION';
export const REMOVE_USER_PERMISSION = 'REMOVE_USER_PERMISSION';
export const ADD_REQUEST = 'ADD_REQUEST';
