export const ACTIVE_USER_ACCOUNT_HASH_RECEIVED = 'ACTIVE_USER_ACCOUNT_HASH_RECEIVED';

export const FETCH_PROFILE_IDS = 'FETCH_PROFILE_IDS';
export const PROFILE_IDS_RECEIVED = 'PROFILE_IDS_RECEIVED';
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const PROFILE_RECEIVED = 'PROFILE_RECEIVED';
export const PROFILE_REMOVED = 'PROFILE_REMOVED';

export const REQUEST_USER_PERMISSION = 'REQUEST_USER_PERMISSION';
export const USER_PERMISSION_RECEIVED = 'USER_PERMISSION_RECEIVED';

export const REFILL_ACCOUNT = 'REFILL_ACCOUNT';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const REMOVE_PROFILE = 'REMOVE_PROFILE';
export const ADD_PROFILE = 'ADD_PROFILE';
export const ADD_USER_PERMISSION = 'ADD_USER_PERMISSION';
export const REMOVE_USER_PERMISSION = 'REMOVE_USER_PERMISSION';
export const ADD_TRANSACTION_REQUEST = 'ADD_TRANSACTION_REQUEST';

export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS';
export const FETCH_TRANSACTION = 'FETCH_TRANSACTION';
export const TRANSACTION_RECEIVED = 'TRANSACTION_RECEIVED';
export const SEND_VOTE = 'SEND_VOTE';
